src/Entity/Parametre.php
<?php

namespace App\Entity;

use App\Repository\ParametreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParametreRepository::class)
 */
class Parametre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $header;

    /**
     * @ORM\Column(type="text")
     */
    private $accroche;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $footer;

   

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $introTitre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $introText;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $widgetText;

    /**
     * @ORM\ManyToOne(targetEntity=Images::class, inversedBy="parametres")
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footerfacebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footerTwitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $FooterLinkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footerTitre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $footerText;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footerDribbble;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footerGithub;

    
    public function getId(): ?int
    {
        return $this->id;
    }

  

    public function getAccroche(): ?string
    {
        return $this->accroche;
    }

    public function setAccroche(string $accroche): self
    {
        $this->accroche = $accroche;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getHeader(): ?string
    {
        return $this->header;
    }

    public function setHeader(string $header): self
    {
        $this->header = $header;

        return $this;
    }

    public function getFooter(): ?string
    {
        return $this->footer;
    }

    public function setFooter(string $footer): self
    {
        $this->footer = $footer;

        return $this;
    }

    
    public function getIntroTitre(): ?string
    {
        return $this->introTitre;
    }

    public function setIntroTitre(?string $introTitre): self
    {
        $this->introTitre = $introTitre;

        return $this;
    }

    public function getIntroText(): ?string
    {
        return $this->introText;
    }

    public function setIntroText(?string $introText): self
    {
        $this->introText = $introText;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getWidgetText(): ?string
    {
        return $this->widgetText;
    }

    public function setWidgetText(?string $widgetText): self
    {
        $this->widgetText = $widgetText;

        return $this;
    }

    public function getLogo(): ?Images
    {
        return $this->logo;
    }

    public function setLogo(?Images $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getFooterfacebook(): ?string
    {
        return $this->footerfacebook;
    }

    public function setFooterfacebook(?string $footerfacebook): self
    {
        $this->footerfacebook = $footerfacebook;

        return $this;
    }

    public function getFooterTwitter(): ?string
    {
        return $this->footerTwitter;
    }

    public function setFooterTwitter(?string $footerTwitter): self
    {
        $this->footerTwitter = $footerTwitter;

        return $this;
    }

    public function getFooterLinkedin(): ?string
    {
        return $this->FooterLinkedin;
    }

    public function setFooterLinkedin(?string $FooterLinkedin): self
    {
        $this->FooterLinkedin = $FooterLinkedin;

        return $this;
    }

    public function getFooterTitre(): ?string
    {
        return $this->footerTitre;
    }

    public function setFooterTitre(?string $footerTitre): self
    {
        $this->footerTitre = $footerTitre;

        return $this;
    }

    public function getFooterText(): ?string
    {
        return $this->footerText;
    }

    public function setFooterText(?string $footerText): self
    {
        $this->footerText = $footerText;

        return $this;
    }

    public function getFooterDribbble(): ?string
    {
        return $this->footerDribbble;
    }

    public function setFooterDribbble(?string $footerDribbble): self
    {
        $this->footerDribbble = $footerDribbble;

        return $this;
    }

    public function getFooterGithub(): ?string
    {
        return $this->footerGithub;
    }

    public function setFooterGithub(?string $footerGithub): self
    {
        $this->footerGithub = $footerGithub;

        return $this;
    }

  
    
}

templates/common/breadcrumb.html.twig
<ol class="breadcrumb">
	<li><a href="index.html">Home</a></li>
	<li class="active">About</li>
</ol>

templates/common/footer.html.twig
<footer id="footer">
		<div class="footer1">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						<h3 class="widget-title">{% trans %}Contact{% endtrans %}</h3>
						<div class="widget-body">
							<p>{{parametre.telephone}}<br>
								<a href="mailto:#">{{parametre.email}}</a><br>
								<br>
								{{ parametre.adresse | raw }}
							</p>	
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">{% trans %}Follow me{% endtrans %}</h3>
						<div class="widget-body">
							<p class="follow-me-icons clearfix">
							{% if parametre.footerLinkedin is not null %}
								<a href="{{parametre.footerLinkedin}}" target="_blank"><i class="fa fa-linkedin fa-2"></i></a>
							{% endif %}
							{% if parametre.footerTwitter is not null %}
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
							{% endif %}
							{% if parametre.footerDribbble is not null %}
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
							{% endif %}
							{% if parametre.footerGithub is not null %}
								<a href=""><i class="fa fa-github fa-2"></i></a>
							{% endif %}
							{% if parametre.footerFacebook is not null %}
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							{% endif %}
							</p>	
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">{{ parametre.footerTitre }}</h3>
						<div class="widget-body">
							{{ parametre.footerText | raw }}
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="{{path('app_home')}}">{% trans %}Home{% endtrans %}</a> |
								{% if is_granted('ROLE_ADMIN') %}
								<a href="{{path('admin_home')}}">{% trans %}Admin dashboard{% endtrans %}</a> |
								{% else %}
								<a href="{{path('app_home')}}">{% trans %}About{% endtrans %}</a> |
								<a href="{{path('contact_new')}}">{% trans %}Contact{% endtrans %}</a> |
								{% endif %}
								{% if is_granted('ROLE_USER') %}
         		   				<a class="navbar-link" href="{{path('app_logout')}}">{% trans %}Sign out{% endtrans %}</a>
								{% else %}
								<a  href="{{path('app_login')}}">{% trans %}Sign in{% endtrans %}</a> |
								<a  href="{{path('app_register')}}">{% trans %}Sign up{% endtrans %}</a>
								{% endif %}
								
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2021, {{parametre.titre}}
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>
	</footer>	

templates/common/formContact.html.twig
<style>
.labelcategory{
    padding: 8px 0px;
    font-size: 14px;
line-height: 1.428571429;
}
</style>
<article class="col-sm-9 maincontent">
    <header class="page-header">
        <h1 class="page-title">Me contacter /  demander un devis</h1>
    </header>

    <p>
        Remplissez le formulaire ci-dessous avec quelques informations sur votre projet et je vous répondrai dès que possible. Veuillez m'accorder quelques jours pour répondre. 
    </p>
    <br>
        {{ form_start(form) }}
            <div class="row" style="padding-bottom:10px">
                <div class="col-sm-4">
                    {{ form_row(form.firstname) }}
                </div>
                <div class="col-sm-4">
                    {{ form_row(form.lastname) }}
                </div>
                <div class="col-sm-4">
                    {{ form_row(form.email) }}
                </div>
            </div>
            <div class="row" style="padding-bottom:10px">
                <div class="col-sm-4">
                    {{ form_row(form.phone) }}
                </div>
                <div class="col-sm-8">
                    <div class="col-sm-4 labelcategory">
                       Votre demande concerne :
                    </div>
                    <div class="col-sm-4">
                        {{ form_row(form.category) }}
                    </div>
                </div>
                
            </div>
            <br>
            <div class="row">
                <div class="col-sm-12">
                     {{ form_row(form.message) }}
                </div>
            </div>
            <br>
            <div class="row">
                
                <div class="col-sm-6 text-right">
                    <button class="btn shadow-1 rounded-1 blue small">{{ button_label|default('Envoyer') }}</button>
                </div>
            </div>
            
        {{ form_end(form) }}
</article>

templates/common/googleMap.html.twig
<script src="https://maps.googleapis.com/maps/api/js?key=&amp;sensor=false&amp;extension=.js"></script> 
<script src="{{ asset('assets/js/google-map.js') }}"></script>

templates/common/navbar.html.twig
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
	<div class="container">
		<div class="navbar-header">
			<!-- Button for smallest screens -->
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			<a class="navbar-brand" href="{{path('app_home')}}">
			{% if parametre.logo.name is not null %}
				<img width="100" src="{{ asset('uploads/images/' ~ parametre.logo.name)}}" alt="Proweb Artois">
			{% else %}
				<img width="100" src="{{ asset('assets/images/logo.png')}}" alt="Proweb Artois">
			{% endif %}
			</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav pull-right">
				<li><a href="{{path('app_home')}}">{% trans %}Home{% endtrans %}</a></li>
				<li ><a href="{{path('contact_new')}}">{% trans %}Contact{% endtrans %}</a></li>
				{% if is_granted('ROLE_ADMIN') %}
				<li><a href="{{path('admin_home')}}">{% trans %}Admin dashboard{% endtrans %}</a></li>
				{% endif %}
				{% if is_granted('ROLE_USER') %}
				<li><a href="{{path('user_home')}}">{% trans %}Member dashboard{% endtrans %}</a></li>
			<!--	<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="sidebar-left.html">Left Sidebar</a></li>
						<li><a href="sidebar-right.html">Right Sidebar</a></li>
					</ul>
				</li> -->
				
				{% endif %}
				{% if is_granted('ROLE_USER') %}
         		   <li><a class="navbar-link" href="{{path('app_logout')}}">{% trans %}Sign out{% endtrans %}</a></li>
				{% else %}
					<li><a  href="{{path('app_login')}}">{% trans %}Sign in{% endtrans %}</a></li>
					<li><a  href="{{path('app_register')}}">{% trans %}Sign up{% endtrans %}</a></li>
				{% endif %}
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div> 

templates/common/navbar_email.html.twig
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="index.html">
				<img width="100" src="cid:logo" alt="Proweb Artois">
				</a>
			</div>
			
		</div>
	</div> 

templates/common/sidebar.html.twig
<aside class="col-sm-3 sidebar sidebar-right">

				<div class="widget">
					<h4>Proweb Artois</h4>
					<address>
					<p>Proweb Artois est une entreprise qui existe depuis le 28/02/2011.</p>
					<p>Son activité : Conseil en systèmes informatiques, prestation informatique en régie ou forfait,
réalisation et édition de logiciels informatiques en ingénierie informatique.</p>
					<p>J'accompagne depuis 10 ans mes clients dans leurs besoins spécifiques liés au développement de
leur application Web, intranet et e-commerce, également dans des projets de refonte ou migration
technologique.</p>
					</address>
					<h4>Téléphone:</h4>
					<address>
						06 34 25 74 65
					</address>
				</div>

			</aside>